import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import Link from 'next/link';
import { motion } from "framer-motion"
import Parcours from "../containers/parcours/Parcours";
import Skills from "../containers/skills/Skills";
import Projects from '../containers/projects/Projects';
import Contact from '../containers/contacts/Contact';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Maxime DUROYON</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.navbar}>
          
          <ul className={styles.navbar_content}>
            <li>
              <motion.div
                className={styles.box}
                whileHover={{ scale: 1.07 }}
                transition={{ type: "spring", stiffness: 300, damping: 10 }}
              >
                <a href="#presentation">Présentation</a>
              </motion.div>
            </li>
            <li>
              <motion.div
              className={styles.box}
                whileHover={{ scale: 1.07 }}
                transition={{ type: "spring", stiffness: 300, damping: 10 }}
              >
                <a href="#parcours">Parcours</a>
              </motion.div>
            </li>
            <li>
            <motion.div
                className={styles.box}
                whileHover={{ scale: 1.07 }}
                transition={{ type: "spring", stiffness: 300, damping: 10 }}
              >
                <a href="#projects">Mes projets</a>
              </motion.div>
            </li>
            <li>
            <motion.div
                className={styles.box}
                whileHover={{ scale: 1.07 }}
                transition={{ type: "spring", stiffness: 300, damping: 10 }}
              >
                <a href="#skills">Compétences</a>
              </motion.div>
            </li>
            <li>
            <motion.div
                className={styles.box}
                whileHover={{ scale: 1.07 }}
                transition={{ type: "spring", stiffness: 300, damping: 10 }}
              >
                <a href="#contact">Contact</a>
              </motion.div>
            </li>
          </ul>
        </div>
        <div className={styles.welcome}>
          <div className={styles.welcome_content}>
            <motion.div
              className={styles.wall_me}
              animate={{
                scale: [0, 1, 0.9],
                rotate: [0, 180],
                borderRadius: ["10%","50%"]
              }}
              transition={{
                duration: 1,
                ease: "easeInOut",
                times: [0, 0.2, 0.5, 0.8, 1],
                delay: 0.2
              }}
            />
            <motion.div
              className={styles.me}
              animate={{
                scale: [0, 1.1, 1],
              }}
              transition={{
                duration: 1,
                ease: "easeInOut",
                times: [0, 0.2, 0.5, 0.8, 1]
              }}
            >
              <img  src="./img/me.png" alt=""/>
            </motion.div>
            <div>
              <h1 className={styles.names}>Maxime Duroyon</h1>
              {/* <h2>Développeur web Fullstack</h2> */}
            </div>
          </div>
        </div>
        <div id="parcours" className={styles.content}>
          <h2>Parcours</h2>
          <Parcours />
        </div>
        <div id="skills" className={styles.content}>
          <h2>Compétences</h2>
          <Skills />
        </div>
        <div id="projects" className={styles.content}>
          <h2>Projets</h2>
          <Projects />
        </div>
        <div id="contact" className={styles.content}>
          <h2>Contact</h2>
          <Contact />
        </div>
      </main>
    </>
  )
}
